export const LANGUAGE_OPTIONS = {
  en: 'en',
  sv: 'sv',
} as const;

export const LAYOUT = {
  headerHeight: '4.5rem',
  siderCollapsedWidth: '4rem',
  siderWidth: '17.625rem',
};

export const COUNTRY_CODES = [
  { name: 'Sweden', code: 'SE', phone: '+46' },
  { name: 'United States', code: 'US', phone: '+1' },
  { name: 'United Kingdom', code: 'GB', phone: '+44' },
  { name: 'Canada', code: 'CA', phone: '+1' },
  { name: 'Australia', code: 'AU', phone: '+61' },
  { name: 'China', code: 'CN', phone: '+86' },
  { name: 'Germany', code: 'DE', phone: '+49' },
  { name: 'France', code: 'FR', phone: '+33' },
  { name: 'Japan', code: 'JP', phone: '+81' },
  { name: 'Afghanistan', code: 'AF', phone: '+93' },
  { name: 'Albania', code: 'AL', phone: '+355' },
  { name: 'Algeria', code: 'DZ', phone: '+213' },
  { name: 'Andorra', code: 'AD', phone: '+376' },
  { name: 'Angola', code: 'AO', phone: '+244' },
  { name: 'Argentina', code: 'AR', phone: '+54' },
  { name: 'Armenia', code: 'AM', phone: '+374' },
  { name: 'Austria', code: 'AT', phone: '+43' },
  { name: 'Azerbaijan', code: 'AZ', phone: '+994' },
  { name: 'Bahamas', code: 'BS', phone: '+1-242' },
  { name: 'Bahrain', code: 'BH', phone: '+973' },
  { name: 'Bangladesh', code: 'BD', phone: '+880' },
  { name: 'Barbados', code: 'BB', phone: '+1-246' },
  { name: 'Belarus', code: 'BY', phone: '+375' },
  { name: 'Belgium', code: 'BE', phone: '+32' },
  { name: 'Belize', code: 'BZ', phone: '+501' },
  { name: 'Benin', code: 'BJ', phone: '+229' },
  { name: 'Bhutan', code: 'BT', phone: '+975' },
  { name: 'Bolivia', code: 'BO', phone: '+591' },
  { name: 'Bosnia and Herzegovina', code: 'BA', phone: '+387' },
  { name: 'Botswana', code: 'BW', phone: '+267' },
  { name: 'Brazil', code: 'BR', phone: '+55' },
  { name: 'Brunei', code: 'BN', phone: '+673' },
  { name: 'Bulgaria', code: 'BG', phone: '+359' },
  { name: 'Burkina Faso', code: 'BF', phone: '+226' },
  { name: 'Burundi', code: 'BI', phone: '+257' },
  { name: 'Cambodia', code: 'KH', phone: '+855' },
  { name: 'Cameroon', code: 'CM', phone: '+237' },
  { name: 'Cape Verde', code: 'CV', phone: '+238' },
  { name: 'Central African Republic', code: 'CF', phone: '+236' },
  { name: 'Chad', code: 'TD', phone: '+235' },
  { name: 'Chile', code: 'CL', phone: '+56' },
  { name: 'Colombia', code: 'CO', phone: '+57' },
  { name: 'Comoros', code: 'KM', phone: '+269' },
  { name: 'Congo', code: 'CG', phone: '+242' },
  { name: 'Congo (DRC)', code: 'CD', phone: '+243' },
  { name: 'Costa Rica', code: 'CR', phone: '+506' },
  { name: 'Croatia', code: 'HR', phone: '+385' },
  { name: 'Cuba', code: 'CU', phone: '+53' },
  { name: 'Cyprus', code: 'CY', phone: '+357' },
  { name: 'Czech Republic', code: 'CZ', phone: '+420' },
  { name: 'Denmark', code: 'DK', phone: '+45' },
  { name: 'Djibouti', code: 'DJ', phone: '+253' },
  { name: 'Dominica', code: 'DM', phone: '+1-767' },
  { name: 'Dominican Republic', code: 'DO', phone: '+1-809' },
  { name: 'Ecuador', code: 'EC', phone: '+593' },
  { name: 'Egypt', code: 'EG', phone: '+20' },
  { name: 'El Salvador', code: 'SV', phone: '+503' },
  { name: 'Equatorial Guinea', code: 'GQ', phone: '+240' },
  { name: 'Eritrea', code: 'ER', phone: '+291' },
  { name: 'Estonia', code: 'EE', phone: '+372' },
  { name: 'Ethiopia', code: 'ET', phone: '+251' },
  { name: 'Fiji', code: 'FJ', phone: '+679' },
  { name: 'Finland', code: 'FI', phone: '+358' },
  { name: 'Gabon', code: 'GA', phone: '+241' },
  { name: 'Gambia', code: 'GM', phone: '+220' },
  { name: 'Georgia', code: 'GE', phone: '+995' },
  { name: 'Ghana', code: 'GH', phone: '+233' },
  { name: 'Greece', code: 'GR', phone: '+30' },
  { name: 'Grenada', code: 'GD', phone: '+1-473' },
  { name: 'Guatemala', code: 'GT', phone: '+502' },
  { name: 'Guinea', code: 'GN', phone: '+224' },
  { name: 'Guinea-Bissau', code: 'GW', phone: '+245' },
  { name: 'Guyana', code: 'GY', phone: '+592' },
  { name: 'Haiti', code: 'HT', phone: '+509' },
  { name: 'Honduras', code: 'HN', phone: '+504' },
  { name: 'Hong Kong', code: 'HK', phone: '+852' },
  { name: 'Hungary', code: 'HU', phone: '+36' },
  { name: 'Iceland', code: 'IS', phone: '+354' },
  { name: 'India', code: 'IN', phone: '+91' },
  { name: 'Indonesia', code: 'ID', phone: '+62' },
  { name: 'Iran', code: 'IR', phone: '+98' },
  { name: 'Iraq', code: 'IQ', phone: '+964' },
  { name: 'Ireland', code: 'IE', phone: '+353' },
  { name: 'Italy', code: 'IT', phone: '+39' },
  { name: 'Ivory Coast', code: 'CI', phone: '+225' },
  { name: 'Jamaica', code: 'JM', phone: '+1-876' },
  { name: 'Jordan', code: 'JO', phone: '+962' },
  { name: 'Kazakhstan', code: 'KZ', phone: '+7' },
  { name: 'Kenya', code: 'KE', phone: '+254' },
  { name: 'Kiribati', code: 'KI', phone: '+686' },
  { name: 'Kosovo', code: 'XK', phone: '+383' },
  { name: 'Kuwait', code: 'KW', phone: '+965' },
  { name: 'Kyrgyzstan', code: 'KG', phone: '+996' },
  { name: 'Laos', code: 'LA', phone: '+856' },
  { name: 'Latvia', code: 'LV', phone: '+371' },
  { name: 'Lebanon', code: 'LB', phone: '+961' },
  { name: 'Lesotho', code: 'LS', phone: '+266' },
  { name: 'Liberia', code: 'LR', phone: '+231' },
  { name: 'Libya', code: 'LY', phone: '+218' },
  { name: 'Liechtenstein', code: 'LI', phone: '+423' },
  { name: 'Lithuania', code: 'LT', phone: '+370' },
  { name: 'Luxembourg', code: 'LU', phone: '+352' },
  { name: 'Macau', code: 'MO', phone: '+853' },
  { name: 'Macedonia', code: 'MK', phone: '+389' },
  { name: 'Madagascar', code: 'MG', phone: '+261' },
  { name: 'Malawi', code: 'MW', phone: '+265' },
  { name: 'Malaysia', code: 'MY', phone: '+60' },
  { name: 'Maldives', code: 'MV', phone: '+960' },
  { name: 'Mali', code: 'ML', phone: '+223' },
  { name: 'Malta', code: 'MT', phone: '+356' },
  { name: 'Marshall Islands', code: 'MH', phone: '+692' },
  { name: 'Mauritania', code: 'MR', phone: '+222' },
  { name: 'Mauritius', code: 'MU', phone: '+230' },
  { name: 'Mexico', code: 'MX', phone: '+52' },
  { name: 'Micronesia', code: 'FM', phone: '+691' },
  { name: 'Moldova', code: 'MD', phone: '+373' },
  { name: 'Monaco', code: 'MC', phone: '+377' },
  { name: 'Mongolia', code: 'MN', phone: '+976' },
  { name: 'Montenegro', code: 'ME', phone: '+382' },
  { name: 'Morocco', code: 'MA', phone: '+212' },
  { name: 'Mozambique', code: 'MZ', phone: '+258' },
  { name: 'Myanmar', code: 'MM', phone: '+95' },
  { name: 'Namibia', code: 'NA', phone: '+264' },
  { name: 'Nauru', code: 'NR', phone: '+674' },
  { name: 'Nepal', code: 'NP', phone: '+977' },
  { name: 'Netherlands', code: 'NL', phone: '+31' },
  { name: 'New Zealand', code: 'NZ', phone: '+64' },
  { name: 'Nicaragua', code: 'NI', phone: '+505' },
  { name: 'Niger', code: 'NE', phone: '+227' },
  { name: 'Nigeria', code: 'NG', phone: '+234' },
  { name: 'North Korea', code: 'KP', phone: '+850' },
  { name: 'Norway', code: 'NO', phone: '+47' },
  { name: 'Oman', code: 'OM', phone: '+968' },
  { name: 'Pakistan', code: 'PK', phone: '+92' },
  { name: 'Palau', code: 'PW', phone: '+680' },
  { name: 'Palestine', code: 'PS', phone: '+970' },
  { name: 'Panama', code: 'PA', phone: '+507' },
  { name: 'Papua New Guinea', code: 'PG', phone: '+675' },
  { name: 'Paraguay', code: 'PY', phone: '+595' },
  { name: 'Peru', code: 'PE', phone: '+51' },
  { name: 'Philippines', code: 'PH', phone: '+63' },
  { name: 'Poland', code: 'PL', phone: '+48' },
  { name: 'Portugal', code: 'PT', phone: '+351' },
  { name: 'Qatar', code: 'QA', phone: '+974' },
  { name: 'Romania', code: 'RO', phone: '+40' },
  { name: 'Russia', code: 'RU', phone: '+7' },
  { name: 'Rwanda', code: 'RW', phone: '+250' },
  { name: 'Saint Kitts and Nevis', code: 'KN', phone: '+1-869' },
  { name: 'Saint Lucia', code: 'LC', phone: '+1-758' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC', phone: '+1-784' },
  { name: 'Samoa', code: 'WS', phone: '+685' },
  { name: 'San Marino', code: 'SM', phone: '+378' },
  { name: 'Sao Tome and Principe', code: 'ST', phone: '+239' },
  { name: 'Saudi Arabia', code: 'SA', phone: '+966' },
  { name: 'Senegal', code: 'SN', phone: '+221' },
  { name: 'Serbia', code: 'RS', phone: '+381' },
  { name: 'Seychelles', code: 'SC', phone: '+248' },
  { name: 'Sierra Leone', code: 'SL', phone: '+232' },
  { name: 'Singapore', code: 'SG', phone: '+65' },
  { name: 'Slovakia', code: 'SK', phone: '+421' },
  { name: 'Slovenia', code: 'SI', phone: '+386' },
  { name: 'Solomon Islands', code: 'SB', phone: '+677' },
  { name: 'Somalia', code: 'SO', phone: '+252' },
  { name: 'South Africa', code: 'ZA', phone: '+27' },
  { name: 'South Korea', code: 'KR', phone: '+82' },
  { name: 'South Sudan', code: 'SS', phone: '+211' },
  { name: 'Spain', code: 'ES', phone: '+34' },
  { name: 'Sri Lanka', code: 'LK', phone: '+94' },
  { name: 'Sudan', code: 'SD', phone: '+249' },
  { name: 'Suriname', code: 'SR', phone: '+597' },
  { name: 'Swaziland', code: 'SZ', phone: '+268' },
  { name: 'Switzerland', code: 'CH', phone: '+41' },
  { name: 'Syria', code: 'SY', phone: '+963' },
  { name: 'Taiwan', code: 'TW', phone: '+886' },
  { name: 'Tajikistan', code: 'TJ', phone: '+992' },
  { name: 'Tanzania', code: 'TZ', phone: '+255' },
  { name: 'Thailand', code: 'TH', phone: '+66' },
  { name: 'Timor-Leste', code: 'TL', phone: '+670' },
  { name: 'Togo', code: 'TG', phone: '+228' },
  { name: 'Tonga', code: 'TO', phone: '+676' },
  { name: 'Trinidad and Tobago', code: 'TT', phone: '+1-868' },
  { name: 'Tunisia', code: 'TN', phone: '+216' },
  { name: 'Turkey', code: 'TR', phone: '+90' },
  { name: 'Turkmenistan', code: 'TM', phone: '+993' },
  { name: 'Tuvalu', code: 'TV', phone: '+688' },
  { name: 'Uganda', code: 'UG', phone: '+256' },
  { name: 'Ukraine', code: 'UA', phone: '+380' },
  { name: 'United Arab Emirates', code: 'AE', phone: '+971' },
  { name: 'United Kingdom', code: 'GB', phone: '+44' },
  { name: 'Uruguay', code: 'UY', phone: '+598' },
  { name: 'Uzbekistan', code: 'UZ', phone: '+998' },
  { name: 'Vanuatu', code: 'VU', phone: '+678' },
  { name: 'Vatican City', code: 'VA', phone: '+379' },
  { name: 'Venezuela', code: 'VE', phone: '+58' },
  { name: 'Vietnam', code: 'VN', phone: '+84' },
  { name: 'Yemen', code: 'YE', phone: '+967' },
  { name: 'Zambia', code: 'ZM', phone: '+260' },
  { name: 'Zimbabwe', code: 'ZW', phone: '+263' },
];

export const CURRENCY_CODES = [
  // Major Currencies (Most Used)
  { code: 'USD', symbol: '$', name: 'United States Dollar' },
  { code: 'EUR', symbol: '€', name: 'Euro' },
  { code: 'GBP', symbol: '£', name: 'British Pound Sterling' },
  { code: 'JPY', symbol: '¥', name: 'Japanese Yen' },
  { code: 'CHF', symbol: 'CHF', name: 'Swiss Franc' },
  { code: 'CAD', symbol: 'C$', name: 'Canadian Dollar' },
  { code: 'AUD', symbol: 'A$', name: 'Australian Dollar' },
  { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar' },
  { code: 'CNY', symbol: '¥', name: 'Chinese Yuan' },
  { code: 'SEK', symbol: 'kr', name: 'Swedish Krona' },

  // Asia-Pacific
  { code: 'INR', symbol: '₹', name: 'Indian Rupee' },
  { code: 'KRW', symbol: '₩', name: 'South Korean Won' },
  { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar' },
  { code: 'HKD', symbol: 'HK$', name: 'Hong Kong Dollar' },
  { code: 'TWD', symbol: 'NT$', name: 'New Taiwan Dollar' },
  { code: 'THB', symbol: '฿', name: 'Thai Baht' },
  { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit' },
  { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah' },
  { code: 'PHP', symbol: '₱', name: 'Philippine Peso' },
  { code: 'VND', symbol: '₫', name: 'Vietnamese Dong' },
  { code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka' },
  { code: 'PKR', symbol: '₨', name: 'Pakistani Rupee' },
  { code: 'LKR', symbol: '₨', name: 'Sri Lankan Rupee' },
  { code: 'NPR', symbol: '₨', name: 'Nepalese Rupee' },
  { code: 'MMK', symbol: 'K', name: 'Myanmar Kyat' },
  { code: 'KHR', symbol: '៛', name: 'Cambodian Riel' },
  { code: 'LAK', symbol: '₭', name: 'Lao Kip' },
  { code: 'BND', symbol: 'B$', name: 'Brunei Dollar' },
  { code: 'MOP', symbol: 'MOP$', name: 'Macanese Pataca' },
  { code: 'MNT', symbol: '₮', name: 'Mongolian Tugrik' },

  // Middle East
  { code: 'SAR', symbol: '﷼', name: 'Saudi Riyal' },
  { code: 'AED', symbol: 'د.إ', name: 'United Arab Emirates Dirham' },
  { code: 'QAR', symbol: 'ر.ق', name: 'Qatari Riyal' },
  { code: 'KWD', symbol: 'د.ك', name: 'Kuwaiti Dinar' },
  { code: 'BHD', symbol: '.د.ب', name: 'Bahraini Dinar' },
  { code: 'OMR', symbol: 'ر.ع.', name: 'Omani Rial' },
  { code: 'JOD', symbol: 'د.ا', name: 'Jordanian Dinar' },
  { code: 'IQD', symbol: 'ع.د', name: 'Iraqi Dinar' },
  { code: 'IRR', symbol: '﷼', name: 'Iranian Rial' },
  { code: 'LBP', symbol: 'ل.ل', name: 'Lebanese Pound' },
  { code: 'SYP', symbol: '£S', name: 'Syrian Pound' },
  { code: 'YER', symbol: '﷼', name: 'Yemeni Rial' },

  // Europe
  { code: 'RUB', symbol: '₽', name: 'Russian Ruble' },
  { code: 'TRY', symbol: '₺', name: 'Turkish Lira' },
  { code: 'PLN', symbol: 'zł', name: 'Polish Zloty' },
  { code: 'NOK', symbol: 'kr', name: 'Norwegian Krone' },
  { code: 'DKK', symbol: 'kr', name: 'Danish Krone' },
  { code: 'CZK', symbol: 'Kč', name: 'Czech Koruna' },
  { code: 'HUF', symbol: 'Ft', name: 'Hungarian Forint' },
  { code: 'RON', symbol: 'lei', name: 'Romanian Leu' },
  { code: 'BGN', symbol: 'лв', name: 'Bulgarian Lev' },
  { code: 'HRK', symbol: 'kn', name: 'Croatian Kuna' },
  { code: 'ISK', symbol: 'kr', name: 'Icelandic Króna' },
  { code: 'UAH', symbol: '₴', name: 'Ukrainian Hryvnia' },
  { code: 'BYN', symbol: 'Br', name: 'Belarusian Ruble' },
  { code: 'MKD', symbol: 'ден', name: 'Macedonian Denar' },
  { code: 'RSD', symbol: 'дин', name: 'Serbian Dinar' },
  {
    code: 'BAM',
    symbol: 'KM',
    name: 'Bosnia and Herzegovina Convertible Mark',
  },
  { code: 'ALL', symbol: 'L', name: 'Albanian Lek' },
  { code: 'MDL', symbol: 'L', name: 'Moldovan Leu' },
  { code: 'GEL', symbol: '₾', name: 'Georgian Lari' },
  { code: 'AMD', symbol: '֏', name: 'Armenian Dram' },
  { code: 'AZN', symbol: '₼', name: 'Azerbaijani Manat' },
  { code: 'KGS', symbol: 'лв', name: 'Kyrgyzstani Som' },
  { code: 'KZT', symbol: '₸', name: 'Kazakhstani Tenge' },
  { code: 'UZS', symbol: 'soʻm', name: 'Uzbekistani Som' },
  { code: 'TJS', symbol: 'ЅМ', name: 'Tajikistani Somoni' },
  { code: 'TMT', symbol: 'm', name: 'Turkmenistani Manat' },

  // Africa
  { code: 'ZAR', symbol: 'R', name: 'South African Rand' },
  { code: 'EGP', symbol: '£', name: 'Egyptian Pound' },
  { code: 'NGN', symbol: '₦', name: 'Nigerian Naira' },
  { code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling' },
  { code: 'GHS', symbol: '₵', name: 'Ghanaian Cedi' },
  { code: 'TZS', symbol: 'TSh', name: 'Tanzanian Shilling' },
  { code: 'UGX', symbol: 'USh', name: 'Ugandan Shilling' },
  { code: 'MAD', symbol: 'د.م.', name: 'Moroccan Dirham' },
  { code: 'TND', symbol: 'د.ت.', name: 'Tunisian Dinar' },
  { code: 'DZD', symbol: 'دج', name: 'Algerian Dinar' },
  { code: 'ETB', symbol: 'Br', name: 'Ethiopian Birr' },
  { code: 'AOA', symbol: 'Kz', name: 'Angolan Kwanza' },
  { code: 'MZN', symbol: 'MT', name: 'Mozambican Metical' },
  { code: 'ZMW', symbol: 'ZK', name: 'Zambian Kwacha' },
  { code: 'ZWL', symbol: 'Z$', name: 'Zimbabwean Dollar' },
  { code: 'BWP', symbol: 'P', name: 'Botswana Pula' },
  { code: 'MUR', symbol: '₨', name: 'Mauritian Rupee' },
  { code: 'NAD', symbol: 'N$', name: 'Namibian Dollar' },
  { code: 'SCR', symbol: '₨', name: 'Seychellois Rupee' },
  { code: 'RWF', symbol: 'FRw', name: 'Rwandan Franc' },
  { code: 'LYD', symbol: 'ل.د', name: 'Libyan Dinar' },
  { code: 'SDG', symbol: 'ج.س.', name: 'Sudanese Pound' },
  { code: 'SSP', symbol: '£', name: 'South Sudanese Pound' },
  { code: 'SOS', symbol: 'Sh', name: 'Somali Shilling' },
  { code: 'DJF', symbol: 'Fdj', name: 'Djiboutian Franc' },
  { code: 'ERN', symbol: 'Nfk', name: 'Eritrean Nakfa' },
  { code: 'GMD', symbol: 'D', name: 'Gambian Dalasi' },
  { code: 'GNF', symbol: 'FG', name: 'Guinean Franc' },
  { code: 'LRD', symbol: 'L$', name: 'Liberian Dollar' },
  { code: 'SLL', symbol: 'Le', name: 'Sierra Leonean Leone' },
  { code: 'MWK', symbol: 'MK', name: 'Malawian Kwacha' },
  { code: 'LSL', symbol: 'L', name: 'Lesotho Loti' },
  { code: 'SZL', symbol: 'L', name: 'Swazi Lilangeni' },
  { code: 'MGA', symbol: 'Ar', name: 'Malagasy Ariary' },
  { code: 'KMF', symbol: 'CF', name: 'Comorian Franc' },
  { code: 'CVE', symbol: '$', name: 'Cape Verdean Escudo' },
  { code: 'STN', symbol: 'Db', name: 'São Tomé and Príncipe Dobra' },
  { code: 'BIF', symbol: 'FBu', name: 'Burundian Franc' },
  { code: 'CDF', symbol: 'FC', name: 'Congolese Franc' },
  { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc' },
  { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc' },

  // Americas
  { code: 'BRL', symbol: 'R$', name: 'Brazilian Real' },
  { code: 'MXN', symbol: '$', name: 'Mexican Peso' },
  { code: 'ARS', symbol: '$', name: 'Argentine Peso' },
  { code: 'CLP', symbol: '$', name: 'Chilean Peso' },
  { code: 'COP', symbol: '$', name: 'Colombian Peso' },
  { code: 'PEN', symbol: 'S/', name: 'Peruvian Sol' },
  { code: 'VES', symbol: 'Bs.S', name: 'Venezuelan Bolívar' },
  { code: 'BOB', symbol: 'Bs.', name: 'Bolivian Boliviano' },
  { code: 'PYG', symbol: '₲', name: 'Paraguayan Guaraní' },
  { code: 'UYU', symbol: '$U', name: 'Uruguayan Peso' },
  { code: 'GYD', symbol: 'G$', name: 'Guyanese Dollar' },
  { code: 'SRD', symbol: '$', name: 'Surinamese Dollar' },
  { code: 'CRC', symbol: '₡', name: 'Costa Rican Colón' },
  { code: 'GTQ', symbol: 'Q', name: 'Guatemalan Quetzal' },
  { code: 'HNL', symbol: 'L', name: 'Honduran Lempira' },
  { code: 'NIO', symbol: 'C$', name: 'Nicaraguan Córdoba' },
  { code: 'PAB', symbol: 'B/.', name: 'Panamanian Balboa' },
  { code: 'DOP', symbol: 'RD$', name: 'Dominican Peso' },
  { code: 'CUP', symbol: '$', name: 'Cuban Peso' },
  { code: 'CUC', symbol: 'CUC$', name: 'Cuban Convertible Peso' },
  { code: 'HTG', symbol: 'G', name: 'Haitian Gourde' },
  { code: 'JMD', symbol: 'J$', name: 'Jamaican Dollar' },
  { code: 'TTD', symbol: 'TT$', name: 'Trinidad and Tobago Dollar' },
  { code: 'BBD', symbol: 'Bds$', name: 'Barbadian Dollar' },
  { code: 'BSD', symbol: 'B$', name: 'Bahamian Dollar' },
  { code: 'BZD', symbol: 'BZ$', name: 'Belize Dollar' },
  { code: 'XCD', symbol: 'EC$', name: 'East Caribbean Dollar' },
  { code: 'AWG', symbol: 'ƒ', name: 'Aruban Florin' },
  { code: 'ANG', symbol: 'ƒ', name: 'Netherlands Antillean Guilder' },

  // Oceania
  { code: 'FJD', symbol: 'FJ$', name: 'Fijian Dollar' },
  { code: 'PGK', symbol: 'K', name: 'Papua New Guinean Kina' },
  { code: 'TOP', symbol: 'T$', name: 'Tongan Paʻanga' },
  { code: 'WST', symbol: 'WS$', name: 'Samoan Tala' },
  { code: 'VUV', symbol: 'VT', name: 'Vanuatu Vatu' },
  { code: 'SBD', symbol: 'SI$', name: 'Solomon Islands Dollar' },
  { code: 'XPF', symbol: 'CFPF', name: 'CFP Franc' },

  // Other Territories & Special Cases
  { code: 'AFN', symbol: '؋', name: 'Afghan Afghani' },
  { code: 'BTN', symbol: 'Nu.', name: 'Bhutanese Ngultrum' },
  { code: 'MVR', symbol: 'Rf', name: 'Maldivian Rufiyaa' },
  { code: 'KPW', symbol: '₩', name: 'North Korean Won' },
  { code: 'GIP', symbol: '£', name: 'Gibraltar Pound' },
  { code: 'FKP', symbol: '£', name: 'Falkland Islands Pound' },
  { code: 'SHP', symbol: '£', name: 'Saint Helena Pound' },
];
