export const PIRATES = [
  {
    id: '1',
    name: 'Monkey D. Luffy',
    username: 'strawhat_luffy',
    status: 'Active',
    role: 'Captain',
    email: 'luffy@strawhatpirates.com',
    teams: ['Straw Hat Pirates', 'Worst Generation'],
    avatar: '/assets/dummy/images/luffy-dp.png',
  },
  {
    id: '2',
    name: 'Roronoa Zoro',
    username: 'pirate_hunter',
    status: 'Active',
    role: 'Swordsman',
    email: 'zoro@strawhatpirates.com',
    teams: ['Straw Hat Pirates', 'Worst Generation'],
    avatar: '/assets/dummy/images/zoro-dp.webp',
  },
  {
    id: '3',
    name: 'Nami',
    username: 'cat_burglar',
    status: 'Active',
    role: 'Navigator',
    email: 'nami@strawhatpirates.com',
    teams: ['Straw Hat Pirates'],
    avatar: '/assets/dummy/images/nami-dp.webp',
  },
  {
    id: '4',
    name: 'Sanji Vinsmoke',
    username: 'black_leg',
    status: 'Active',
    role: 'Cook',
    email: 'sanji@strawhatpirates.com',
    teams: ['Straw Hat Pirates'],
    avatar: '/assets/dummy/images/sanji-dp.webp',
  },
  {
    id: '5',
    name: 'Tony Tony Chopper',
    username: 'cotton_candy_lover',
    status: 'Active',
    role: 'Doctor',
    email: 'chopper@strawhatpirates.com',
    teams: ['Straw Hat Pirates'],
    avatar: '/assets/dummy/images/chopper-dp.webp',
  },
  {
    id: '6',
    name: 'Nico Robin',
    username: 'devil_child',
    status: 'Active',
    role: 'Archaeologist',
    email: 'robin@strawhatpirates.com',
    teams: ['Straw Hat Pirates'],
    avatar: '/assets/dummy/images/robin-dp.webp',
  },
  {
    id: '7',
    name: 'Franky',
    username: 'cyborg_franky',
    status: 'Active',
    role: 'Shipwright',
    email: 'franky@strawhatpirates.com',
    teams: ['Straw Hat Pirates', 'Franky Family'],
    avatar: '/assets/dummy/images/franky-dp.webp',
  },
  {
    id: '8',
    name: 'Brook',
    username: 'soul_king',
    status: 'Inactive',
    role: 'Musician',
    email: 'brook@strawhatpirates.com',
    teams: ['Straw Hat Pirates'],
    avatar: '/assets/dummy/images/brook-dp.png',
  },
  {
    id: '9',
    name: 'Jinbe',
    username: 'first_son_of_sea',
    status: 'Active',
    role: 'Helmsman',
    email: 'jinbe@strawhatpirates.com',
    teams: ['Straw Hat Pirates', 'Sun Pirates'],
    avatar: '/assets/dummy/images/jinbe-dp.webp',
  },
  {
    id: '10',
    name: 'Trafalgar D. Water Law',
    username: 'surgeon_of_death',
    status: 'Inactive',
    role: 'Captain',
    email: 'law@heartpirates.com',
    teams: ['Heart Pirates', 'Worst Generation'],
    avatar: '/assets/dummy/images/law-dp.webp',
  },
];
