/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as PublicLoginRouteImport } from './routes/_public/login';
import { Route as DashboardRouteImport } from './routes/dashboard';
import { Route as DashboardAntdDemosRouteImport } from './routes/dashboard/antd-demos';
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index';
import { Route as IndexRouteImport } from './routes/index';

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardAntdDemosRoute = DashboardAntdDemosRouteImport.update({
  id: '/antd-demos',
  path: '/antd-demos',
  getParentRoute: () => DashboardRoute,
} as any);
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/_public/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/dashboard': typeof DashboardRouteWithChildren;
  '/login': typeof PublicLoginRoute;
  '/dashboard/antd-demos': typeof DashboardAntdDemosRoute;
  '/dashboard/': typeof DashboardIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/login': typeof PublicLoginRoute;
  '/dashboard/antd-demos': typeof DashboardAntdDemosRoute;
  '/dashboard': typeof DashboardIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/dashboard': typeof DashboardRouteWithChildren;
  '/_public/login': typeof PublicLoginRoute;
  '/dashboard/antd-demos': typeof DashboardAntdDemosRoute;
  '/dashboard/': typeof DashboardIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/antd-demos'
    | '/dashboard/';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/login' | '/dashboard/antd-demos' | '/dashboard';
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/_public/login'
    | '/dashboard/antd-demos'
    | '/dashboard/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardRoute: typeof DashboardRouteWithChildren;
  PublicLoginRoute: typeof PublicLoginRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/dashboard/': {
      id: '/dashboard/';
      path: '/';
      fullPath: '/dashboard/';
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    '/dashboard/antd-demos': {
      id: '/dashboard/antd-demos';
      path: '/antd-demos';
      fullPath: '/dashboard/antd-demos';
      preLoaderRoute: typeof DashboardAntdDemosRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    '/_public/login': {
      id: '/_public/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof PublicLoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface DashboardRouteChildren {
  DashboardAntdDemosRoute: typeof DashboardAntdDemosRoute;
  DashboardIndexRoute: typeof DashboardIndexRoute;
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAntdDemosRoute: DashboardAntdDemosRoute,
  DashboardIndexRoute: DashboardIndexRoute,
};

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  PublicLoginRoute: PublicLoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
