/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as PublicLoginRouteImport } from './routes/_public/login';
import { Route as ComponentsRouteImport } from './routes/components';
import { Route as ComponentsAvatarLabelGroupIndexRouteImport } from './routes/components/avatar-label-group/index';
import { Route as ComponentsAvatarIndexRouteImport } from './routes/components/avatar/index';
import { Route as ComponentsBadgeIndexRouteImport } from './routes/components/badge/index';
import { Route as ComponentsButtonGroupIndexRouteImport } from './routes/components/button-group/index';
import { Route as ComponentsButtonIndexRouteImport } from './routes/components/button/index';
import { Route as ComponentsCheckboxIndexRouteImport } from './routes/components/checkbox/index';
import { Route as ComponentsDropdownIndexRouteImport } from './routes/components/dropdown/index';
import { Route as ComponentsIndexRouteImport } from './routes/components/index';
import { Route as ComponentsInputCopyTextIndexRouteImport } from './routes/components/input-copy-text/index';
import { Route as ComponentsInputNumberIndexRouteImport } from './routes/components/input-number/index';
import { Route as ComponentsInputPhoneNumberIndexRouteImport } from './routes/components/input-phone-number/index';
import { Route as ComponentsInputIndexRouteImport } from './routes/components/input/index';
import { Route as ComponentsModalsIndexRouteImport } from './routes/components/modals/index';
import { Route as ComponentsPaginationsIndexRouteImport } from './routes/components/paginations/index';
import { Route as ComponentsProgressIndexRouteImport } from './routes/components/progress/index';
import { Route as ComponentsSelectIndexRouteImport } from './routes/components/select/index';
import { Route as ComponentsSliderIndexRouteImport } from './routes/components/slider/index';
import { Route as ComponentsTableIndexRouteImport } from './routes/components/table/index';
import { Route as ComponentsTabsIndexRouteImport } from './routes/components/tabs/index';
import { Route as ComponentsTextIndexRouteImport } from './routes/components/text/index';
import { Route as ComponentsToggleIndexRouteImport } from './routes/components/toggle/index';
import { Route as ComponentsTooltipIndexRouteImport } from './routes/components/tooltip/index';
import { Route as DashboardRouteImport } from './routes/dashboard';
import { Route as DashboardAntdDemosRouteImport } from './routes/dashboard/antd-demos';
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index';
import { Route as IndexRouteImport } from './routes/index';

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any);
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any);
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComponentsRoute,
} as any);
const DashboardAntdDemosRoute = DashboardAntdDemosRouteImport.update({
  id: '/antd-demos',
  path: '/antd-demos',
  getParentRoute: () => DashboardRoute,
} as any);
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/_public/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const ComponentsTooltipIndexRoute = ComponentsTooltipIndexRouteImport.update({
  id: '/tooltip/',
  path: '/tooltip/',
  getParentRoute: () => ComponentsRoute,
} as any);
const ComponentsToggleIndexRoute = ComponentsToggleIndexRouteImport.update({
  id: '/toggle/',
  path: '/toggle/',
  getParentRoute: () => ComponentsRoute,
} as any);
const ComponentsTextIndexRoute = ComponentsTextIndexRouteImport.update({
  id: '/text/',
  path: '/text/',
  getParentRoute: () => ComponentsRoute,
} as any);
const ComponentsTabsIndexRoute = ComponentsTabsIndexRouteImport.update({
  id: '/tabs/',
  path: '/tabs/',
  getParentRoute: () => ComponentsRoute,
} as any);
const ComponentsTableIndexRoute = ComponentsTableIndexRouteImport.update({
  id: '/table/',
  path: '/table/',
  getParentRoute: () => ComponentsRoute,
} as any);
const ComponentsSliderIndexRoute = ComponentsSliderIndexRouteImport.update({
  id: '/slider/',
  path: '/slider/',
  getParentRoute: () => ComponentsRoute,
} as any);
const ComponentsSelectIndexRoute = ComponentsSelectIndexRouteImport.update({
  id: '/select/',
  path: '/select/',
  getParentRoute: () => ComponentsRoute,
} as any);
const ComponentsProgressIndexRoute = ComponentsProgressIndexRouteImport.update({
  id: '/progress/',
  path: '/progress/',
  getParentRoute: () => ComponentsRoute,
} as any);
const ComponentsPaginationsIndexRoute =
  ComponentsPaginationsIndexRouteImport.update({
    id: '/paginations/',
    path: '/paginations/',
    getParentRoute: () => ComponentsRoute,
  } as any);
const ComponentsModalsIndexRoute = ComponentsModalsIndexRouteImport.update({
  id: '/modals/',
  path: '/modals/',
  getParentRoute: () => ComponentsRoute,
} as any);
const ComponentsInputIndexRoute = ComponentsInputIndexRouteImport.update({
  id: '/input/',
  path: '/input/',
  getParentRoute: () => ComponentsRoute,
} as any);
const ComponentsInputPhoneNumberIndexRoute =
  ComponentsInputPhoneNumberIndexRouteImport.update({
    id: '/input-phone-number/',
    path: '/input-phone-number/',
    getParentRoute: () => ComponentsRoute,
  } as any);
const ComponentsInputNumberIndexRoute =
  ComponentsInputNumberIndexRouteImport.update({
    id: '/input-number/',
    path: '/input-number/',
    getParentRoute: () => ComponentsRoute,
  } as any);
const ComponentsInputCopyTextIndexRoute =
  ComponentsInputCopyTextIndexRouteImport.update({
    id: '/input-copy-text/',
    path: '/input-copy-text/',
    getParentRoute: () => ComponentsRoute,
  } as any);
const ComponentsDropdownIndexRoute = ComponentsDropdownIndexRouteImport.update({
  id: '/dropdown/',
  path: '/dropdown/',
  getParentRoute: () => ComponentsRoute,
} as any);
const ComponentsCheckboxIndexRoute = ComponentsCheckboxIndexRouteImport.update({
  id: '/checkbox/',
  path: '/checkbox/',
  getParentRoute: () => ComponentsRoute,
} as any);
const ComponentsButtonIndexRoute = ComponentsButtonIndexRouteImport.update({
  id: '/button/',
  path: '/button/',
  getParentRoute: () => ComponentsRoute,
} as any);
const ComponentsButtonGroupIndexRoute =
  ComponentsButtonGroupIndexRouteImport.update({
    id: '/button-group/',
    path: '/button-group/',
    getParentRoute: () => ComponentsRoute,
  } as any);
const ComponentsBadgeIndexRoute = ComponentsBadgeIndexRouteImport.update({
  id: '/badge/',
  path: '/badge/',
  getParentRoute: () => ComponentsRoute,
} as any);
const ComponentsAvatarIndexRoute = ComponentsAvatarIndexRouteImport.update({
  id: '/avatar/',
  path: '/avatar/',
  getParentRoute: () => ComponentsRoute,
} as any);
const ComponentsAvatarLabelGroupIndexRoute =
  ComponentsAvatarLabelGroupIndexRouteImport.update({
    id: '/avatar-label-group/',
    path: '/avatar-label-group/',
    getParentRoute: () => ComponentsRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/components': typeof ComponentsRouteWithChildren;
  '/dashboard': typeof DashboardRouteWithChildren;
  '/login': typeof PublicLoginRoute;
  '/dashboard/antd-demos': typeof DashboardAntdDemosRoute;
  '/components/': typeof ComponentsIndexRoute;
  '/dashboard/': typeof DashboardIndexRoute;
  '/components/avatar-label-group': typeof ComponentsAvatarLabelGroupIndexRoute;
  '/components/avatar': typeof ComponentsAvatarIndexRoute;
  '/components/badge': typeof ComponentsBadgeIndexRoute;
  '/components/button-group': typeof ComponentsButtonGroupIndexRoute;
  '/components/button': typeof ComponentsButtonIndexRoute;
  '/components/checkbox': typeof ComponentsCheckboxIndexRoute;
  '/components/dropdown': typeof ComponentsDropdownIndexRoute;
  '/components/input-copy-text': typeof ComponentsInputCopyTextIndexRoute;
  '/components/input-number': typeof ComponentsInputNumberIndexRoute;
  '/components/input-phone-number': typeof ComponentsInputPhoneNumberIndexRoute;
  '/components/input': typeof ComponentsInputIndexRoute;
  '/components/modals': typeof ComponentsModalsIndexRoute;
  '/components/paginations': typeof ComponentsPaginationsIndexRoute;
  '/components/progress': typeof ComponentsProgressIndexRoute;
  '/components/select': typeof ComponentsSelectIndexRoute;
  '/components/slider': typeof ComponentsSliderIndexRoute;
  '/components/table': typeof ComponentsTableIndexRoute;
  '/components/tabs': typeof ComponentsTabsIndexRoute;
  '/components/text': typeof ComponentsTextIndexRoute;
  '/components/toggle': typeof ComponentsToggleIndexRoute;
  '/components/tooltip': typeof ComponentsTooltipIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/login': typeof PublicLoginRoute;
  '/dashboard/antd-demos': typeof DashboardAntdDemosRoute;
  '/components': typeof ComponentsIndexRoute;
  '/dashboard': typeof DashboardIndexRoute;
  '/components/avatar-label-group': typeof ComponentsAvatarLabelGroupIndexRoute;
  '/components/avatar': typeof ComponentsAvatarIndexRoute;
  '/components/badge': typeof ComponentsBadgeIndexRoute;
  '/components/button-group': typeof ComponentsButtonGroupIndexRoute;
  '/components/button': typeof ComponentsButtonIndexRoute;
  '/components/checkbox': typeof ComponentsCheckboxIndexRoute;
  '/components/dropdown': typeof ComponentsDropdownIndexRoute;
  '/components/input-copy-text': typeof ComponentsInputCopyTextIndexRoute;
  '/components/input-number': typeof ComponentsInputNumberIndexRoute;
  '/components/input-phone-number': typeof ComponentsInputPhoneNumberIndexRoute;
  '/components/input': typeof ComponentsInputIndexRoute;
  '/components/modals': typeof ComponentsModalsIndexRoute;
  '/components/paginations': typeof ComponentsPaginationsIndexRoute;
  '/components/progress': typeof ComponentsProgressIndexRoute;
  '/components/select': typeof ComponentsSelectIndexRoute;
  '/components/slider': typeof ComponentsSliderIndexRoute;
  '/components/table': typeof ComponentsTableIndexRoute;
  '/components/tabs': typeof ComponentsTabsIndexRoute;
  '/components/text': typeof ComponentsTextIndexRoute;
  '/components/toggle': typeof ComponentsToggleIndexRoute;
  '/components/tooltip': typeof ComponentsTooltipIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/components': typeof ComponentsRouteWithChildren;
  '/dashboard': typeof DashboardRouteWithChildren;
  '/_public/login': typeof PublicLoginRoute;
  '/dashboard/antd-demos': typeof DashboardAntdDemosRoute;
  '/components/': typeof ComponentsIndexRoute;
  '/dashboard/': typeof DashboardIndexRoute;
  '/components/avatar-label-group/': typeof ComponentsAvatarLabelGroupIndexRoute;
  '/components/avatar/': typeof ComponentsAvatarIndexRoute;
  '/components/badge/': typeof ComponentsBadgeIndexRoute;
  '/components/button-group/': typeof ComponentsButtonGroupIndexRoute;
  '/components/button/': typeof ComponentsButtonIndexRoute;
  '/components/checkbox/': typeof ComponentsCheckboxIndexRoute;
  '/components/dropdown/': typeof ComponentsDropdownIndexRoute;
  '/components/input-copy-text/': typeof ComponentsInputCopyTextIndexRoute;
  '/components/input-number/': typeof ComponentsInputNumberIndexRoute;
  '/components/input-phone-number/': typeof ComponentsInputPhoneNumberIndexRoute;
  '/components/input/': typeof ComponentsInputIndexRoute;
  '/components/modals/': typeof ComponentsModalsIndexRoute;
  '/components/paginations/': typeof ComponentsPaginationsIndexRoute;
  '/components/progress/': typeof ComponentsProgressIndexRoute;
  '/components/select/': typeof ComponentsSelectIndexRoute;
  '/components/slider/': typeof ComponentsSliderIndexRoute;
  '/components/table/': typeof ComponentsTableIndexRoute;
  '/components/tabs/': typeof ComponentsTabsIndexRoute;
  '/components/text/': typeof ComponentsTextIndexRoute;
  '/components/toggle/': typeof ComponentsToggleIndexRoute;
  '/components/tooltip/': typeof ComponentsTooltipIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/components'
    | '/dashboard'
    | '/login'
    | '/dashboard/antd-demos'
    | '/components/'
    | '/dashboard/'
    | '/components/avatar-label-group'
    | '/components/avatar'
    | '/components/badge'
    | '/components/button-group'
    | '/components/button'
    | '/components/checkbox'
    | '/components/dropdown'
    | '/components/input-copy-text'
    | '/components/input-number'
    | '/components/input-phone-number'
    | '/components/input'
    | '/components/modals'
    | '/components/paginations'
    | '/components/progress'
    | '/components/select'
    | '/components/slider'
    | '/components/table'
    | '/components/tabs'
    | '/components/text'
    | '/components/toggle'
    | '/components/tooltip';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/login'
    | '/dashboard/antd-demos'
    | '/components'
    | '/dashboard'
    | '/components/avatar-label-group'
    | '/components/avatar'
    | '/components/badge'
    | '/components/button-group'
    | '/components/button'
    | '/components/checkbox'
    | '/components/dropdown'
    | '/components/input-copy-text'
    | '/components/input-number'
    | '/components/input-phone-number'
    | '/components/input'
    | '/components/modals'
    | '/components/paginations'
    | '/components/progress'
    | '/components/select'
    | '/components/slider'
    | '/components/table'
    | '/components/tabs'
    | '/components/text'
    | '/components/toggle'
    | '/components/tooltip';
  id:
    | '__root__'
    | '/'
    | '/components'
    | '/dashboard'
    | '/_public/login'
    | '/dashboard/antd-demos'
    | '/components/'
    | '/dashboard/'
    | '/components/avatar-label-group/'
    | '/components/avatar/'
    | '/components/badge/'
    | '/components/button-group/'
    | '/components/button/'
    | '/components/checkbox/'
    | '/components/dropdown/'
    | '/components/input-copy-text/'
    | '/components/input-number/'
    | '/components/input-phone-number/'
    | '/components/input/'
    | '/components/modals/'
    | '/components/paginations/'
    | '/components/progress/'
    | '/components/select/'
    | '/components/slider/'
    | '/components/table/'
    | '/components/tabs/'
    | '/components/text/'
    | '/components/toggle/'
    | '/components/tooltip/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ComponentsRoute: typeof ComponentsRouteWithChildren;
  DashboardRoute: typeof DashboardRouteWithChildren;
  PublicLoginRoute: typeof PublicLoginRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/components': {
      id: '/components';
      path: '/components';
      fullPath: '/components';
      preLoaderRoute: typeof ComponentsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/dashboard/': {
      id: '/dashboard/';
      path: '/';
      fullPath: '/dashboard/';
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    '/components/': {
      id: '/components/';
      path: '/';
      fullPath: '/components/';
      preLoaderRoute: typeof ComponentsIndexRouteImport;
      parentRoute: typeof ComponentsRoute;
    };
    '/dashboard/antd-demos': {
      id: '/dashboard/antd-demos';
      path: '/antd-demos';
      fullPath: '/dashboard/antd-demos';
      preLoaderRoute: typeof DashboardAntdDemosRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    '/_public/login': {
      id: '/_public/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof PublicLoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/components/tooltip/': {
      id: '/components/tooltip/';
      path: '/tooltip';
      fullPath: '/components/tooltip';
      preLoaderRoute: typeof ComponentsTooltipIndexRouteImport;
      parentRoute: typeof ComponentsRoute;
    };
    '/components/toggle/': {
      id: '/components/toggle/';
      path: '/toggle';
      fullPath: '/components/toggle';
      preLoaderRoute: typeof ComponentsToggleIndexRouteImport;
      parentRoute: typeof ComponentsRoute;
    };
    '/components/text/': {
      id: '/components/text/';
      path: '/text';
      fullPath: '/components/text';
      preLoaderRoute: typeof ComponentsTextIndexRouteImport;
      parentRoute: typeof ComponentsRoute;
    };
    '/components/tabs/': {
      id: '/components/tabs/';
      path: '/tabs';
      fullPath: '/components/tabs';
      preLoaderRoute: typeof ComponentsTabsIndexRouteImport;
      parentRoute: typeof ComponentsRoute;
    };
    '/components/table/': {
      id: '/components/table/';
      path: '/table';
      fullPath: '/components/table';
      preLoaderRoute: typeof ComponentsTableIndexRouteImport;
      parentRoute: typeof ComponentsRoute;
    };
    '/components/slider/': {
      id: '/components/slider/';
      path: '/slider';
      fullPath: '/components/slider';
      preLoaderRoute: typeof ComponentsSliderIndexRouteImport;
      parentRoute: typeof ComponentsRoute;
    };
    '/components/select/': {
      id: '/components/select/';
      path: '/select';
      fullPath: '/components/select';
      preLoaderRoute: typeof ComponentsSelectIndexRouteImport;
      parentRoute: typeof ComponentsRoute;
    };
    '/components/progress/': {
      id: '/components/progress/';
      path: '/progress';
      fullPath: '/components/progress';
      preLoaderRoute: typeof ComponentsProgressIndexRouteImport;
      parentRoute: typeof ComponentsRoute;
    };
    '/components/paginations/': {
      id: '/components/paginations/';
      path: '/paginations';
      fullPath: '/components/paginations';
      preLoaderRoute: typeof ComponentsPaginationsIndexRouteImport;
      parentRoute: typeof ComponentsRoute;
    };
    '/components/modals/': {
      id: '/components/modals/';
      path: '/modals';
      fullPath: '/components/modals';
      preLoaderRoute: typeof ComponentsModalsIndexRouteImport;
      parentRoute: typeof ComponentsRoute;
    };
    '/components/input/': {
      id: '/components/input/';
      path: '/input';
      fullPath: '/components/input';
      preLoaderRoute: typeof ComponentsInputIndexRouteImport;
      parentRoute: typeof ComponentsRoute;
    };
    '/components/input-phone-number/': {
      id: '/components/input-phone-number/';
      path: '/input-phone-number';
      fullPath: '/components/input-phone-number';
      preLoaderRoute: typeof ComponentsInputPhoneNumberIndexRouteImport;
      parentRoute: typeof ComponentsRoute;
    };
    '/components/input-number/': {
      id: '/components/input-number/';
      path: '/input-number';
      fullPath: '/components/input-number';
      preLoaderRoute: typeof ComponentsInputNumberIndexRouteImport;
      parentRoute: typeof ComponentsRoute;
    };
    '/components/input-copy-text/': {
      id: '/components/input-copy-text/';
      path: '/input-copy-text';
      fullPath: '/components/input-copy-text';
      preLoaderRoute: typeof ComponentsInputCopyTextIndexRouteImport;
      parentRoute: typeof ComponentsRoute;
    };
    '/components/dropdown/': {
      id: '/components/dropdown/';
      path: '/dropdown';
      fullPath: '/components/dropdown';
      preLoaderRoute: typeof ComponentsDropdownIndexRouteImport;
      parentRoute: typeof ComponentsRoute;
    };
    '/components/checkbox/': {
      id: '/components/checkbox/';
      path: '/checkbox';
      fullPath: '/components/checkbox';
      preLoaderRoute: typeof ComponentsCheckboxIndexRouteImport;
      parentRoute: typeof ComponentsRoute;
    };
    '/components/button/': {
      id: '/components/button/';
      path: '/button';
      fullPath: '/components/button';
      preLoaderRoute: typeof ComponentsButtonIndexRouteImport;
      parentRoute: typeof ComponentsRoute;
    };
    '/components/button-group/': {
      id: '/components/button-group/';
      path: '/button-group';
      fullPath: '/components/button-group';
      preLoaderRoute: typeof ComponentsButtonGroupIndexRouteImport;
      parentRoute: typeof ComponentsRoute;
    };
    '/components/badge/': {
      id: '/components/badge/';
      path: '/badge';
      fullPath: '/components/badge';
      preLoaderRoute: typeof ComponentsBadgeIndexRouteImport;
      parentRoute: typeof ComponentsRoute;
    };
    '/components/avatar/': {
      id: '/components/avatar/';
      path: '/avatar';
      fullPath: '/components/avatar';
      preLoaderRoute: typeof ComponentsAvatarIndexRouteImport;
      parentRoute: typeof ComponentsRoute;
    };
    '/components/avatar-label-group/': {
      id: '/components/avatar-label-group/';
      path: '/avatar-label-group';
      fullPath: '/components/avatar-label-group';
      preLoaderRoute: typeof ComponentsAvatarLabelGroupIndexRouteImport;
      parentRoute: typeof ComponentsRoute;
    };
  }
}

interface ComponentsRouteChildren {
  ComponentsIndexRoute: typeof ComponentsIndexRoute;
  ComponentsAvatarLabelGroupIndexRoute: typeof ComponentsAvatarLabelGroupIndexRoute;
  ComponentsAvatarIndexRoute: typeof ComponentsAvatarIndexRoute;
  ComponentsBadgeIndexRoute: typeof ComponentsBadgeIndexRoute;
  ComponentsButtonGroupIndexRoute: typeof ComponentsButtonGroupIndexRoute;
  ComponentsButtonIndexRoute: typeof ComponentsButtonIndexRoute;
  ComponentsCheckboxIndexRoute: typeof ComponentsCheckboxIndexRoute;
  ComponentsDropdownIndexRoute: typeof ComponentsDropdownIndexRoute;
  ComponentsInputCopyTextIndexRoute: typeof ComponentsInputCopyTextIndexRoute;
  ComponentsInputNumberIndexRoute: typeof ComponentsInputNumberIndexRoute;
  ComponentsInputPhoneNumberIndexRoute: typeof ComponentsInputPhoneNumberIndexRoute;
  ComponentsInputIndexRoute: typeof ComponentsInputIndexRoute;
  ComponentsModalsIndexRoute: typeof ComponentsModalsIndexRoute;
  ComponentsPaginationsIndexRoute: typeof ComponentsPaginationsIndexRoute;
  ComponentsProgressIndexRoute: typeof ComponentsProgressIndexRoute;
  ComponentsSelectIndexRoute: typeof ComponentsSelectIndexRoute;
  ComponentsSliderIndexRoute: typeof ComponentsSliderIndexRoute;
  ComponentsTableIndexRoute: typeof ComponentsTableIndexRoute;
  ComponentsTabsIndexRoute: typeof ComponentsTabsIndexRoute;
  ComponentsTextIndexRoute: typeof ComponentsTextIndexRoute;
  ComponentsToggleIndexRoute: typeof ComponentsToggleIndexRoute;
  ComponentsTooltipIndexRoute: typeof ComponentsTooltipIndexRoute;
}

const ComponentsRouteChildren: ComponentsRouteChildren = {
  ComponentsIndexRoute: ComponentsIndexRoute,
  ComponentsAvatarLabelGroupIndexRoute: ComponentsAvatarLabelGroupIndexRoute,
  ComponentsAvatarIndexRoute: ComponentsAvatarIndexRoute,
  ComponentsBadgeIndexRoute: ComponentsBadgeIndexRoute,
  ComponentsButtonGroupIndexRoute: ComponentsButtonGroupIndexRoute,
  ComponentsButtonIndexRoute: ComponentsButtonIndexRoute,
  ComponentsCheckboxIndexRoute: ComponentsCheckboxIndexRoute,
  ComponentsDropdownIndexRoute: ComponentsDropdownIndexRoute,
  ComponentsInputCopyTextIndexRoute: ComponentsInputCopyTextIndexRoute,
  ComponentsInputNumberIndexRoute: ComponentsInputNumberIndexRoute,
  ComponentsInputPhoneNumberIndexRoute: ComponentsInputPhoneNumberIndexRoute,
  ComponentsInputIndexRoute: ComponentsInputIndexRoute,
  ComponentsModalsIndexRoute: ComponentsModalsIndexRoute,
  ComponentsPaginationsIndexRoute: ComponentsPaginationsIndexRoute,
  ComponentsProgressIndexRoute: ComponentsProgressIndexRoute,
  ComponentsSelectIndexRoute: ComponentsSelectIndexRoute,
  ComponentsSliderIndexRoute: ComponentsSliderIndexRoute,
  ComponentsTableIndexRoute: ComponentsTableIndexRoute,
  ComponentsTabsIndexRoute: ComponentsTabsIndexRoute,
  ComponentsTextIndexRoute: ComponentsTextIndexRoute,
  ComponentsToggleIndexRoute: ComponentsToggleIndexRoute,
  ComponentsTooltipIndexRoute: ComponentsTooltipIndexRoute,
};

const ComponentsRouteWithChildren = ComponentsRoute._addFileChildren(
  ComponentsRouteChildren
);

interface DashboardRouteChildren {
  DashboardAntdDemosRoute: typeof DashboardAntdDemosRoute;
  DashboardIndexRoute: typeof DashboardIndexRoute;
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAntdDemosRoute: DashboardAntdDemosRoute,
  DashboardIndexRoute: DashboardIndexRoute,
};

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsRoute: ComponentsRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  PublicLoginRoute: PublicLoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
